AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Resources:
  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: serverless.HelloWorld
      Runtime: java8
      Role: arn:aws:iam::ACCOUNT_NUMBER:role/LambdaFullAccessRole
